export const labels = {
  es: {
    nav: [
      "Inicio",
      "Sobre mí",
      "Habilidades",
      "Proyectos",
      "Trayectoria",
      "Contacto",
    ],
    hello: "Hola, soy",
    headline: "Convierto ideas en",
    highlight: "experiencias digitales.",
    intro:
      "Desarrollo soluciones web de principio a fin. Del detalle en la interfaz a la arquitectura que lo hace posible.",
    work: "Explorar proyectos",
    cv: "Descargar CV",
    about: "UN POCO SOBRE MÍ",
    aboutTitle: "La curiosidad me mueve.",
    aboutAccent: "El código le da forma.",
    more: "Más sobre mí",
    stats: ["Años de experiencia", "Tecnologías", "Formación", "Proyectos"],
    skills: "MI CAJA DE HERRAMIENTAS",
    skillsTitle: "Tecnología con propósito.",
    skillsText:
      "Las herramientas con las que transformo desafíos en soluciones.",
    tech: "Tecnologías",
    snake: {
      gameTitle: "Diviértete mientras conoces nuevas tecnologías.",
      play: "Jugar Tech-Snake",
      intro: "¿Quieres jugar algo y conocer nuevas tecnologías?",
      mobileIntro:
        "¿Quieres jugar algo y conocer nuevas tecnologías? Ingresa desde un computador para jugar Tech-Snake.",
      welcomeTitle: "Bienvenido a Tech-Snake!",
      welcomeBody:
        "Para jugar elige una dirección con las flechas, WASD o los controles sobre el tablero para comenzar.",
      welcomeAction: "A jugar y aprender!",
      resultWonTitle: "¡Felicitaciones!",
      resultWonBody:
        "Capturaste todas las tecnologías que aparecieron en el tablero.",
      resultLostTitle: "La partida terminó.",
      resultLostBody: "Estas son las tecnologías que alcanzaste a capturar.",
      resultEmpty: "Vuelve a intentarlo!",
      resultCaptured: "Tecnologías capturadas",
      technologyDescriptions: {
        Redis: "Almacén de datos en memoria usado para caché y mensajería.",
        Kubernetes:
          "Plataforma para automatizar el despliegue y la gestión de contenedores.",
        AWS: "Plataforma en la nube con servicios de infraestructura y aplicaciones.",
        Go: "Lenguaje compilado, simple y eficiente creado por Google.",
        Rust: "Lenguaje de sistemas centrado en rendimiento y seguridad de memoria.",
        RabbitMQ:
          "Broker de mensajes para conectar servicios de forma asíncrona.",
      },
      instructions:
        "Elige una dirección con las flechas, WASD o los controles para comenzar.",
      score: "Tecnologías descubiertas",
      pause: "Pausar",
      paused: "Juego en pausa. Pulsa continuar cuando estés listo.",
      resume: "Continuar",
      restart: "Reiniciar",
      exit: "Salir del juego",
      gameOver: "Fin del juego. Reinicia para intentarlo otra vez.",
      won: "¡Completaste todas las tecnologías!",
      food: "NUEVA",
      moveUp: "Mover arriba",
      moveDown: "Mover abajo",
      moveLeft: "Mover a la izquierda",
      moveRight: "Mover a la derecha",
    },
    levels: "Autoevaluación de habilidades",
    projects: "PROYECTOS SELECCIONADOS",
    projectsTitle: "Ideas que se hicieron realidad.",
    projectsText: "Una selección de lo que he ayudado a construir.",
    repo: "Ver repositorio",
    company: "Visitar empresa",
    career: "MI RECORRIDO",
    careerTitle: "Aprender. Construir. Evolucionar.",
    experience: "Experiencia",
    education: "Educación",
    interests: "FUERA DEL EDITOR",
    interestsTitle: "También hay vida después del código.",
    contact: "CONSTRUYAMOS ALGO JUNTOS",
    contactTitle: "¿Tienes una idea en mente?",
    contactText:
      "Conversemos sobre tu próximo proyecto y cómo puedo ayudarte a hacerlo realidad.",
    contactButton: "Hablemos",
    social: "ENCUÉNTRAME EN",
    contactMe: "Contáctame en:",
    emailLabel: "Enviar correo",
    rights: "Todos los derechos reservados.",
    made: "Hecho con curiosidad y código.",
    theme: "Tema",
    themes: ["Claro", "Oscuro", "Sistema"],
    language: "Idioma",
    menu: "Abrir menú",
    skip: "Saltar al contenido",
    english: "Inglés",
    details: "Logros y tecnologías",
  },
  en: {
    nav: ["Home", "About", "Skills", "Projects", "Journey", "Contact"],
    hello: "Hi, I’m",
    headline: "Turning ideas into",
    highlight: "digital experiences.",
    intro:
      "I build web solutions from end to end. From the details in the interface to the architecture that makes it all work.",
    work: "Explore projects",
    cv: "Download CV",
    about: "A LITTLE ABOUT ME",
    aboutTitle: "Driven by curiosity.",
    aboutAccent: "Brought to life in code.",
    more: "More about me",
    stats: ["Years of experience", "Technologies", "Education", "Projects"],
    skills: "MY TOOLKIT",
    skillsTitle: "Technology with purpose.",
    skillsText: "The tools I use to turn challenges into solutions.",
    tech: "Technologies",
    snake: {
      gameTitle: "Have fun while discovering new technologies.",
      play: "Play Tech-Snake",
      intro: "Want to play something and discover new technologies?",
      mobileIntro:
        "Want to play something and discover new technologies? Use a computer to play Tech-Snake.",
      welcomeTitle: "Welcome to Tech-Snake!",
      welcomeBody:
        "Choose a direction with the arrow keys, WASD, or the controls above the board to start playing.",
      welcomeAction: "Play and learn!",
      resultWonTitle: "Congratulations!",
      resultWonBody:
        "You captured every technology that appeared on the board.",
      resultLostTitle: "Game over.",
      resultLostBody: "These are the technologies you managed to capture.",
      resultEmpty: "Try again!",
      resultCaptured: "Captured technologies",
      technologyDescriptions: {
        Redis: "An in-memory data store used for caching and messaging.",
        Kubernetes:
          "A platform for automating container deployment and management.",
        AWS: "A cloud platform with infrastructure and application services.",
        Go: "A simple, efficient compiled language created by Google.",
        Rust: "A systems language focused on performance and memory safety.",
        RabbitMQ: "A message broker that connects services asynchronously.",
      },
      instructions:
        "Choose a direction with the arrow keys, WASD, or the controls to begin.",
      score: "Technologies discovered",
      pause: "Pause",
      paused: "Game paused. Press resume when you are ready.",
      resume: "Resume",
      restart: "Restart",
      exit: "Exit game",
      gameOver: "Game over. Restart to try again.",
      won: "You discovered every technology!",
      food: "NEW",
      moveUp: "Move up",
      moveDown: "Move down",
      moveLeft: "Move left",
      moveRight: "Move right",
    },
    levels: "Self-assessed proficiency",
    projects: "SELECTED PROJECTS",
    projectsTitle: "Ideas brought to life.",
    projectsText: "A selection of things I have helped build.",
    repo: "View repository",
    company: "Visit company",
    career: "MY JOURNEY",
    careerTitle: "Learn. Build. Evolve.",
    experience: "Experience",
    education: "Education",
    interests: "BEYOND THE EDITOR",
    interestsTitle: "There’s life beyond the code.",
    contact: "LET’S BUILD SOMETHING TOGETHER",
    contactTitle: "Have an idea in mind?",
    contactText:
      "Let’s talk about your next project and how I can help bring it to life.",
    contactButton: "Let’s talk",
    social: "FIND ME ON",
    contactMe: "Contact me:",
    emailLabel: "Send email",
    rights: "All rights reserved.",
    made: "Made with curiosity and code.",
    theme: "Theme",
    themes: ["Light", "Dark", "System"],
    language: "Language",
    menu: "Open menu",
    skip: "Skip to content",
    english: "English",
    details: "Achievements and technologies",
  },
};
